name: release ws-server exe

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup py
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller websockets pynput pystray Pillow pyperclip

      - name: build ws-server exe
        run: |
          python -m PyInstaller --onefile --windowed --add-data "ws-server/icon.ico;." --icon="ws-server/icon.ico" --name="input-overlay-ws" ws-server/input-overlay-ws.py

      - name: make release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/input-overlay-ws.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}